//Les MULES
var m1Options={type:"PCCDI", description:"Les admins n'y verront que du feu!", perSecondModifier:1, cost:100};
var m2Options={type:"COUZINDUBLED", description:"Hey tonton! Les cabas y sont trop lourds!", perSecondModifier: 15, cost:1300};
var m3Options={type:"LAN", description:"Bien meilleur qu'une RIK.",perSecondModifier: 100, cost:9800};
var m4Options={type:"BOTNET", description:"Un virus codé pour cliquer sur Kraland.",perSecondModifier: 500, cost:48000};
var m5Options={type:"PIRQTTINOI", description:"Les Métants Tinois tipiaks !",perSecondModifier: 2700, cost:200000};

//Les FONCTIONS
var f1Options={type:"Citoyen", ppModifier:2, chance:70, cost:5, costPDV:5, className:"citoyen", txtChance:"Potentiel : PP/10 =", description:"Vous pouvez usurper un citoyen de la ville et quitter le monde du prolétariat. La difficulté est pas si pire. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du centième du meilleur score à <a href=\"http://games.adultswim.com/robot-unicorn-attack-twitchy-online-game.html\" target=\"_blank\">Robot Uniorn Attack</a> du mec dont on tente d'usurper l'identité (sauf si le mec est une licorne)."};
var f2Options={type:"Juge", ppModifier:5, chance:65, cost:8, costPDV:10, className:"juge", txtChance:"Potentiel : PP/10 =", description:"Vous pouvez usurper le poste de juge de votre ville et prendre cette place. La difficulté est pas super haute et vous devriez vous en sortir. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du dixième de la touffe de ch'veux du fonctionnaire dont on tente d'usurper le poste (sauf si le fonctionnaire est chauve). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f3Options={type:"Bourgmestre", ppModifier:7, chance:60, costPDV:15, cost:12, txtChance:"Potentiel : PP/10 =", className:"bourgmestre", description:"Vous pouvez usurper le poste de bourgmestre de votre ville et prendre cette place. La difficulté commence à pointer le bout de son nez mais avec une bonne PP ça devrait aller <em>chillax nigga</em>. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du quart du nombre de joueurs restants sur Kraland (sauf s'il n'y a plus de joueur). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f4Options={type:"Intendant", ppModifier:9, chance:55, costPDV:20, cost:18, txtChance:"Potentiel : PP/10 =", className:"intendant", description:"Vous pouvez usurper le poste d'intendant de votre province et prendre cette place. La difficulté est là et va falloir faire avec. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée de la tendance du PIB Grec (sauf s'il n'y a plus de Grèce). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f5Options={type:"Gouverneur", ppModifier:15, chance:40, costPDV:25, cost:25, txtChance:"Potentiel : PP/10 =", className:"gouverneur", description:"Vous pouvez usurper le poste de gouverneur de votre province et prendre cette place. La difficulté est chaude mais c'est la saison qui veut ça. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du cosinus de la dernière position sexuelle qui a été effectuée dans un rayon de 5km autour de vous (à l'exception des positions dites <em>onanistes</em>). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f6Options={type:"Inspecteur des Impôts", ppModifier:25, chance:30, costPDV:30, cost:28, txtChance:"Potentiel : PP/10 =", className:"inspecteur", description:"Vous pouvez usurper le poste d'inspecteur des impôts de votre empire et rejoindre une magnifique équipe de P.I.P.E. La difficulté est chaude sa mère. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée de l'ID du dernier mec banni (sauf si c'est un DY car leurs IDs sont bien trop élevés). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f7Options={type:"Ministre de l'Information", ppModifier:30, chance:25, cost:30, costPDV:35, txtChance:"Potentiel : PP/10 =", className:"minfo", description:"Vous pouvez usurper le poste de ministre de l'information de votre empire et prendre cette place. La difficulté est chanmax et va falloir une moule de bâtard pour réussir. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du dernier monoligne de Révolution multiplié par mille (sauf si ce monoligne dépasse les 7 caractères, smileys inclus). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f8Options={type:"Ministre des Affaires Etrangères", ppModifier:40, chance:15, cost:35, costPDV:40, txtChance:"Potentiel : PP/10 =", className:"mae", description:"Vous pouvez usurper le poste de ministre des affaires étragères de votre empire et prendre cette place. La difficulté est <em>toff man</em> et en plus il faut savoir parler plusieurs langues. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du nombre de RP dinettes ayant eu lieu au cours de la dernière heure (sauf si ceux-ci contiennent du RP saiks). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f9Options={type:"Premier Ministre", ppModifier:60, chance:10, cost:40, costPDV:45, txtChance:"Potentiel : PP/10 =", className:"pm", description:"Vous pouvez usurper le poste de premier ministre de votre empire et prendre cette place. La difficulté est <em>harkorr</em> et respect si tu réussis. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du pourcentage de Krach boursier IRL ou IG (ou les deux). De nombreux modificateurs peuvent influencer le potentiel (scripts, amis dans le staff, etc)."};
var f10Options={type:"PREMIER ELU §§", ppModifier:100, chance:1, cost:40, costPDV:70, txtChance:"Potentiel : PP/10 =", className:"prelu", description:"Vous pouvez usurper le poste de PREMIER ELU §§ de votre jeu préféré et prendre cette honorable place. La difficulté est insurmontable mais une fois réussie vous aurez légitimement gagné KI. Vous bénéficiez d'un bonus équivalent au dixième de votre puissance politique. La difficulté est additionnée du nombre de personnes présente à la Tower RIK (sauf si par chance j'y suis). De nombreux modificateurs peuvent influencer le potentiel (scripts, ennemis de red<img src=\"http://img.kraland.org/s/4C.gif\" align=\"middle\">star, etc)."};

//Les ORDRES
var o1Options={type:"Soutien", ppAdd:4, costPDV:5, className:"soutien", fnName:"autoSoutien", description:"Vous pouvez faire un discours de soutien envers vous même parce que vous êtes un abusator et que osef les règles. Votre propre PP augmentera de X/4 mais comme je ne sais pas compter ce sera un chiffre arbitrairement décidé par Random, notre maître à tous.", cost:0, txtChance:"Potentiel : PP/10 + Eloquence =",chance:6};
var o2Options={type:"Consommer", pdvAdd:5, costPDV:0.5, className:"consommer", fnName:"consommerRepasDeLuxe", description:"Vous pouvez acheter et consommer un repas de luxe sur place et en subir les effets. Pas de marchandage possible parce qu'en plus d'être un établissement tombé entre les mains de Zyor Mawi, vous devriez être foutrement riche avec vos mules.", cost:50, txtChance:'Automatique -', chance:100};
var o3Options={type:"AjouterPDVMax", pdvMax:1, costPDV:0, className:"ajoutPdvMax", fnName:"ajoutPdvMax", description:"Vous pouvez augmenter d'1 point votre maximum de points de vie en dépensant du franc-kra parce que les PA ne valent rien ici.", cost:305, txtChance:'Automatique -', chance:100};

//La REGEN
var r1Options={type:"Dodo",regenAdd:0.01, cost:100};
var r2Options={type:"RedBoule",regenAdd:0.05, cost:400};
var r3Options={type:"PastilleBonheur",regenAdd:0.5, cost:2500};
var r4Options={type:"Quebecois",regenAdd:1, cost:10000};

//Facteur chance
var fc1Options={type:"PipedDice",cost:10000,multiplicateur:1.8}